#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SCRIPTS_DIR="${THIS_SCRIPT_DIR}"
source "${SCRIPTS_DIR}/common" # Add the functions in 'common'

testDaemon() {
    message $'\nTesting SSL Daemon...\n'
    cd "${DAEMON_TEST_DIR}"
    ctest --output-on-failure
}

testHttpServer() {
    message $'\nTesting Common library...\n'
    cd "${COMMON_TEST_DIR}"
    ctest --output-on-failure
}

test() {
    COMMON_TEST_DIR="${SERVER_DIR}/build/${COMMON_LIB_NAME}/test"
    DAEMON_TEST_DIR="${SERVER_DIR}/build/${SSL_DAEMON_NAME}/test"

    testHttpServer
    testDaemon
}
