#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SCRIPTS_DIR="${THIS_SCRIPT_DIR}/res/scripts"
source "${SCRIPTS_DIR}/build" # Add the functions in 'build'
source "${SCRIPTS_DIR}/start" # Add the functions in 'start'
source "${SCRIPTS_DIR}/test" # Add the functions in 'test'

usage() {
    echo "USAGE"
    echo "    $0 <OPTION>"
    echo
    echo "OPTIONS"
    echo "    --help  | -h     Print this help menu and exit"
    echo "    --start | -a     Start the Elevation server"
    echo "    --stop  | -o     Stop the Elevation server"
    echo "    --build | -b     Build the Elevation server"
    echo "    --test  | -t     Run all automated tests"
}

runScript() {
    if [ $# != 1 ]; then
        usage
    else
        case $1 in

        -h | --help)
            usage
            ;;

        -a |--start)
            start
            ;;

        -o | --stop)
            stop
            ;;

        -b | --build)
            build
            ;;

        -t | --test)
            test
            ;;

        *)
            echo "Invalid option '$1'"
            echo
            usage
            exit 1
            ;;

        esac
    fi
}

runScript "$@"
