#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SCRIPTS_DIR="${THIS_SCRIPT_DIR}/res/scripts"
source "${SCRIPTS_DIR}/build"  # Add the functions in 'build'
source "${SCRIPTS_DIR}/start"  # Add the functions in 'start'
source "${SCRIPTS_DIR}/clean"  # Add the functions in 'clean'
source "${SCRIPTS_DIR}/test"   # Add the functions in 'test'
source "${SCRIPTS_DIR}/docker" # Add the functions in 'docker'

usage() {
    echo "USAGE"
    echo "    $0 <OPTION | DOCKER OPTION>"
    echo
    echo "OPTIONS"
    echo "     -h | --help     Print this help menu and exit"
    echo "     -a | --start    Start the Elevation server"
    echo "     -r | --run      Start the Elevation server and wait until it terminates"
    echo "     -o | --stop     Stop the Elevation server"
    echo "     -b | --build    Build the Elevation server"
    echo "     -c | --clean    Clean the Elevation server, its logs and its dependencies"
    echo "     -t | --test     Run all automated tests"
    echo
    echo "DOCKER OPTIONS"
    echo "     -i | --create-image     Build docker image"
    echo "     -m | --remove-image     Remove docker image"
    echo "     -n | --run-container    Run docker container"
}

runScript() {
    if [ $# != 1 ]; then
        usage
    else
        case $1 in

        -h | --help)
            usage
            ;;

        -a |--start)
            start
            ;;

        -r |--run)
            run
            ;;

        -o | --stop)
            stop
            ;;

        -b | --build)
            build
            ;;

        -c | --clean)
            clean
            ;;

        -t | --test)
            test
            ;;

        -i | --build-image)
            createImage
            ;;

        -m | --remove-image)
            removeImage
            ;;

        -n | --run-container)
            runContainer
            ;;

        *)
            echo "Invalid option '$1'"
            echo
            usage
            exit 1
            ;;

        esac
    fi
}

runScript "$@"
