#!/bin/bash

SERVER_DIR="$(git rev-parse --show-toplevel)/project/server"
PRIVATE_SOCKETS_DIR="${SERVER_DIR}/build/common/sock"
mkdir -p "${PRIVATE_SOCKETS_DIR}"

# Check if root
if [ "$(whoami)" == root ]; then
    PORT=80
    MAX_PORT=100
else
    PORT=8080
    MAX_PORT=8100
fi

while [ "$PORT" != "$MAX_PORT" ]; do
    echo $'\n'"Trying port number $PORT"
    ./build/http-server/http-server "$PORT"
    RETURN_CODE=$?
    if [ "$RETURN_CODE" == 255 ]; then
        PORT=$(($PORT + 1))
    fi
    if [ "$RETURN_CODE" == 0 ]; then
        break
    fi
done
