PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE user (ip VARCHAR(16), mac VARCHAR(18) UNIQUE, name VARCHAR(256), token VARCHAR(32) UNIQUE);
CREATE TABLE userConnection (token VARCHAR(32) UNIQUE NOT NULL PRIMARY KEY, isConnected INTEGER, timeStamp REAL, FOREIGN KEY(token) REFERENCES user(token));
CREATE TABLE adminLogin (login VARCHAR(256) UNIQUE NOT NULL, hashedPassword VARCHAR(32) NOT NULL, salt VARCHAR(32) NOT NULL, mac VARCHAR(18));
COMMIT;
