PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE user (ip VARCHAR(16), mac VARCHAR(18) UNIQUE, name VARCHAR(256) );
CREATE TABLE song (title VARCHAR(256), artist VARCHAR(256), user_id INTEGER, path VARCHAR(256));
COMMIT;
