#!/usr/bin/env bash

SERVER_DIR="$(git rev-parse --show-toplevel)/project/server"
HTTP_SERVER_TEST_DIR="${SERVER_DIR}/build/http-server/test"
DAEMON_TEST_DIR="${SERVER_DIR}/build/ssl-daemon/test"

message() {
    tput bold 2>/dev/null
    tput setaf 10 2>/dev/null
    echo "$@"
    tput sgr0 2>/dev/null
}

testDaemon() {
    message $'\nTesting SSL Daemon...\n'
    cd "${DAEMON_TEST_DIR}"
    ctest --output-on-failure
}

testHttpServer() {
    message $'\nTesting HTTP Server...\n'
    cd "${HTTP_SERVER_TEST_DIR}"
    ctest --output-on-failure
}

testHttpServer
testDaemon
